apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.9.0
    helm:
      releaseName: karpenter
      values: |
        settings:
          clusterName: lab-eks-dev

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
